export const GET_DETAILS = "GET_DETAILS";
export const SET_DETAILS = "SET_DETAILS";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const POST_PRODUCT = "POST_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";