export const GET_PRODUCT_BY_NAME = "GET_PRODUCT_BY_NAME";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const CHANGE_CART_QUANTITY = "CHANGE_CART_QUANTITY";
